### ISSUE TITLE
Crash Report -1262901788

### ISSUE THREAD

**Issue by jimmyt857** [wowsims/tbc#1006]
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 75 [running]:
runtime/debug.Stack(0x9ed7c0, 0x5ce0d40, 0x40)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/tbc/sim/core.RunSim.func1(0x5d33fd8, 0x57bcf60)
	/home/ubuntu/tbc/sim/core/sim.go:49 +0x8
panic(0x95d60, 0x9ed7c0)
	/usr/local/go/src/runtime/panic.go:965 +0x19
github.com/wowsims/tbc/sim/shaman/elemental.(*AdaptiveRotation).Reset(0x576a000, 0x56b7f80, 0x4ce89a0)
	/home/ubuntu/tbc/sim/shaman/elemental/rotation.go:215 +0x7
github.com/wowsims/tbc/sim/shaman/elemental.(*ElementalShaman).Reset(0x56b7f80, 0x4ce89a0)
	/home/ubuntu/tbc/sim/shaman/elemental/elemental.go:80 +0x7
github.com/wowsims/tbc/sim/core.(*Character).reset(0x5c53000, 0x4ce89a0, 0x1e5af8, 0x56b7f80)
	/home/ubuntu/tbc/sim/core/character.go:317 +0x9
github.com/wowsims/tbc/sim/core.(*Party).reset(0x5c18f00, 0x4ce89a0)
	/home/ubuntu/tbc/sim/core/raid.go:74 +0xa
github.com/wowsims/tbc/sim/core.(*Raid).reset(0x57bcfc0, 0x4ce89a0)
	/home/ubuntu/tbc/sim/core/raid.go:275 +0x7
github.com/wowsims/tbc/sim/core.(*Simulation).reset(0x4ce89a0)
	/home/ubuntu/tbc/sim/core/sim.go:145 +0x1e
github.com/wowsims/tbc/sim/core.(*Simulation).runOnce(0x4ce89a0)
	/home/ubuntu/tbc/sim/core/sim.go:217 +0x2
github.com/wowsims/tbc/sim/core.(*Simulation).run(0x4ce89a0, 0x5cb1210)
	/home/ubuntu/tbc/sim/core/sim.go:181 +0x1b
github.com/wowsims/tbc/sim/core.RunSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4cf1420, 0x57bcf00, 0x5c5d140, 0x57bcf60, 0x0)
	/home/ubuntu/tbc/sim/core/sim.go:72 +0x5
created by github.com/wowsims/tbc/sim/core.RunRaidSimAsync
	/home/ubuntu/tbc/sim/core/api.go:74 +0x4

**Comment by jimmyt857** [comment]
Exported JSON:
{
  "settings": {
    "iterations": 1,
    "phase": 5,
    "showThreatMetrics": true
  },
  "raid": {
    "parties": [
      {
        "players": [
          {},
          {
            "name": "Ele Shaman",
            "race": "RaceDraenei",
            "class": "ClassShaman",
            "equipment": {
              "items": [
                {
                  "id": 34332,
                  "enchant": 29191,
                  "gems": [
                    35761,
                    34220
                  ]
                },
                {
                  "id": 34204
                },
                {
                  "id": 31023,
                  "enchant": 23545,
                  "gems": [
                    32215,
                    35761
                  ]
                },
                {
                  "id": 34242,
                  "enchant": 33150,
                  "gems": [
                    35760
                  ]
                },
                {
                  "id": 34396,
                  "enchant": 24003,
                  "gems": [
                    35760,
                    35761,
                    35761
                  ]
                },
                {
                  "id": 34437,
                  "enchant": 22534,
                  "gems": [
                    35761
                  ]
                },
                {
                  "id": 34350,
                  "enchant": 28272,
                  "gems": [
                    35760,
                    32215
                  ]
                },
                {
                  "id": 34542,
                  "gems": [
                    35761
                  ]
                },
                {
                  "id": 34186,
                  "enchant": 24274,
                  "gems": [
                    35761,
                    35760,
                    35760
                  ]
                },
                {
                  "id": 34566,
                  "enchant": 35297,
                  "gems": [
                    35760
                  ]
                },
                {
                  "id": 34230,
                  "enchant": 22536
                },
                {
                  "id": 32527,
                  "enchant": 22536
                },
                {
                  "id": 34429
                },
                {
                  "id": 33829
                },
                {
                  "id": 34336,
                  "enchant": 22555
                },
                {
                  "id": 34179
                },
                {
                  "id": 32330
                }
              ]
            },
            "consumes": {
              "flask": "FlaskOfBlindingLight",
              "mainHandImbue": "WeaponImbueBrilliantWizardOil",
              "food": "FoodBlackenedBasilisk",
              "defaultPotion": "SuperManaPotion",
              "drums": "DrumsOfBattle"
            },
            "bonusStats": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "buffs": {},
            "talentsString": "55003105100213351051--05105301005",
            "cooldowns": {},
            "elementalShaman": {
              "rotation": {
                "totems": {
                  "earth": "TremorTotem",
                  "air": "WrathOfAirTotem",
                  "fire": "TotemOfWrath",
                  "water": "ManaSpringTotem"
                },
                "type": "Adaptive"
              },
              "talents": {},
              "options": {
                "waterShield": true,
                "bloodlust": true
              }
            }
          },
          {},
          {},
          {
            "name": "Shadow Priest",
            "race": "RaceDwarf",
            "class": "ClassPriest",
            "equipment": {
              "items": [
                {
                  "id": 34340,
                  "enchant": 29191,
                  "gems": [
                    25893,
                    32215
                  ]
                },
                {
                  "id": 34204
                },
                {
                  "id": 31070,
                  "enchant": 28886,
                  "gems": [
                    32196,
                    32196
                  ]
                },
                {
                  "id": 34242,
                  "enchant": 33150,
                  "gems": [
                    32196
                  ]
                },
                {
                  "id": 34232,
                  "enchant": 33990,
                  "gems": [
                    32196,
                    32196,
                    32196
                  ]
                },
                {
                  "id": 34434,
                  "enchant": 22534,
                  "gems": [
                    32196
                  ]
                },
                {
                  "id": 34344,
                  "enchant": 28272,
                  "gems": [
                    32196,
                    32196
                  ]
                },
                {
                  "id": 34528,
                  "gems": [
                    32196
                  ]
                },
                {
                  "id": 34181,
                  "enchant": 24274,
                  "gems": [
                    32196,
                    32196,
                    32196
                  ]
                },
                {
                  "id": 34563,
                  "enchant": 35297,
                  "gems": [
                    32196
                  ]
                },
                {
                  "id": 34230,
                  "enchant": 22536
                },
                {
                  "id": 32527,
                  "enchant": 22536
                },
                {
                  "id": 33829
                },
                {
                  "id": 34429
                },
                {
                  "id": 34336,
                  "enchant": 22561
                },
                {
                  "id": 34179
                },
                {
                  "id": 34347,
                  "gems": [
                    32196
                  ]
                }
              ]
            },
            "consumes": {
              "flask": "FlaskOfPureDeath",
              "mainHandImbue": "WeaponImbueSuperiorWizardOil",
              "food": "FoodBlackenedBasilisk",
              "defaultPotion": "SuperManaPotion"
            },
            "bonusStats": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "buffs": {},
            "talentsString": "500230013--503250510240103051451",
            "cooldowns": {},
            "shadowPriest": {
              "rotation": {
                "rotationType": "Ideal"
              },
              "talents": {},
              "options": {
                "useShadowfiend": true
              }
            }
          }
        ],
        "buffs": {}
      },
      {
        "players": [
          {},
          {},
          {},
          {},
          {}
        ],
        "buffs": {}
      },
      {
        "players": [
          {},
          {},
          {},
          {},
          {}
        ],
        "buffs": {}
      },
      {
        "players": [
          {},
          {},
          {},
          {},
          {}
        ],
        "buffs": {}
      },
      {
        "players": [
          {
            "name": "Prot Warrior",
            "race": "RaceHuman",
            "class": "ClassWarrior",
            "equipment": {
              "items": [
                {
                  "id": 35068,
                  "enchant": 29192,
                  "gems": [
                    32409,
                    32205
                  ]
                },
                {
                  "id": 34178
                },
                {
                  "id": 34388,
                  "enchant": 28910,
                  "gems": [
                    32217,
                    32205
                  ]
                },
                {
                  "id": 34190,
                  "enchant": 34004
                },
                {
                  "id": 35066,
                  "enchant": 24003,
                  "gems": [
                    32217,
                    32217,
                    32205
                  ]
                },
                {
                  "id": 34442,
                  "enchant": 22533,
                  "gems": [
                    32200
                  ]
                },
                {
                  "id": 34378,
                  "enchant": 33153,
                  "gems": [
                    32200,
                    32200
                  ]
                },
                {
                  "id": 34547,
                  "gems": [
                    32212
                  ]
                },
                {
                  "id": 34381,
                  "enchant": 29536,
                  "gems": [
                    32200,
                    32200,
                    32212
                  ]
                },
                {
                  "id": 34568,
                  "enchant": 35297,
                  "gems": [
                    32212
                  ]
                },
                {
                  "id": 34213
                },
                {
                  "id": 32266
                },
                {
                  "id": 31858
                },
                {
                  "id": 34473
                },
                {
                  "id": 34164,
                  "enchant": 22559
                },
                {
                  "id": 34185,
                  "enchant": 28282,
                  "gems": [
                    32212
                  ]
                },
                {
                  "id": 32253
                }
              ]
            },
            "consumes": {
              "flask": "FlaskOfFortification",
              "mainHandImbue": "WeaponImbueAdamantiteSharpeningStone",
              "offHandImbue": "WeaponImbueAdamantiteSharpeningStone",
              "food": "FoodFishermansFeast",
              "scrollOfAgility": 5,
              "scrollOfStrength": 5,
              "scrollOfProtection": 5,
              "defaultPotion": "IronshieldPotion"
            },
            "bonusStats": [
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0
            ],
            "buffs": {},
            "talentsString": "35000301302-03-0055511033010101501351",
            "cooldowns": {},
            "protectionWarrior": {
              "rotation": {
                "demoShout": "DemoShoutMaintain",
                "thunderClap": "ThunderClapMaintain",
                "hsRageThreshold": 30
              },
              "talents": {},
              "options": {
                "shout": "WarriorShoutCommanding",
                "precastShout": true
              }
            }
          },
          {},
          {},
          {},
          {}
        ],
        "buffs": {}
      }
    ],
    "buffs": {},
    "debuffs": {},
    "tanks": [
      {
        "targetIndex": 20
      },
      {
        "targetIndex": -1
      }
    ]
  },
  "blessings": {
    "paladins": [
      {
        "blessings": [
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings",
          "BlessingOfKings"
        ]
      },
      {
        "blessings": [
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfMight",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfSalvation",
          "BlessingOfMight",
          "BlessingOfSalvation",
          "BlessingOfSanctuary",
          "BlessingOfMight"
        ]
      },
      {
        "blessings": [
          "BlessingOfWisdom",
          "BlessingOfWisdom",
          "BlessingOfWisdom",
          "BlessingOfSalvation",
          "BlessingOfWisdom",
          "BlessingOfWisdom",
          "BlessingOfMight",
          "BlessingOfMight",
          "BlessingOfMight",
          "BlessingOfMight",
          "BlessingOfWisdom",
          "BlessingOfSanctuary",
          "BlessingOfMight",
          "BlessingOfWisdom",
          "BlessingOfSanctuary"
        ]
      },
      {
        "blessings": [
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingOfWisdom",
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingOfWisdom",
          "BlessingOfWisdom",
          "BlessingUnknown",
          "BlessingUnknown",
          "BlessingOfWisdom",
          "BlessingOfMight",
          "BlessingUnknown"
        ]
      }
    ]
  },
  "encounter": {
    "duration": 180,
    "durationVariation": 5,
    "executeProportion": 0.2,
    "targets": [
      {
        "level": 73,
        "mobType": "MobTypeDemon",
        "stats": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          320,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          7683,
          0,
          0,
          0,
          54,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "minBaseDamage": 10000,
        "swingSpeed": 2,
        "canCrush": true,
        "parryHaste": true
      }
    ]
  }
}

**Comment by jimmyt857** [comment]
This crash is really weird, it doesn't occur when copying the raid sim request into the go code and running in a test environment.

It's also sensitive to the player positioning, e.g. moving the prot warrior around makes the crash go away.
