### ISSUE TITLE
Crash Report -396836288 2 Blinkstrikes crash the sim

### ISSUE THREAD

**Issue by i1Spook** [wowsims/tbc#1084]
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 11 [running]:
runtime/debug.Stack(0xa3cbb0, 0x4ee5740, 0x40)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/tbc/sim/core.runSim.func1(0x4eddf80, 0x4cc0d20)
	/home/runner/work/tbc/tbc/sim/core/sim.go:53 +0x8
panic(0x99480, 0xa3cbb0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:965 +0x19
github.com/wowsims/tbc/sim/core.(*Spell).Cast(...)
	/home/runner/work/tbc/tbc/sim/core/spell.go:188
github.com/wowsims/tbc/sim/common.init.4.func27.3(0x4ce5200, 0x4de15e0, 0x4ee2820, 0x4ee08c0)
	/home/runner/work/tbc/tbc/sim/common/melee_items.go:870 +0x24
github.com/wowsims/tbc/sim/core.(*auraTracker).OnSpellHitDealt(0x4cd1360, 0x4de15e0, 0x4ee2820, 0x4ee08c0)
	/home/runner/work/tbc/tbc/sim/core/aura.go:642 +0xe
github.com/wowsims/tbc/sim/core.(*SpellEffect).finalize(0x4ee08c0, 0x4de15e0, 0x4ee2820)
	/home/runner/work/tbc/tbc/sim/core/spell_effect.go:214 +0x6b
github.com/wowsims/tbc/sim/core.ApplyEffectFuncDirectDamage.func2(0x4de15e0, 0x4c55b00, 0x4ee2820)
	/home/runner/work/tbc/tbc/sim/core/spell.go:244 +0x16
github.com/wowsims/tbc/sim/core.(*Spell).applyEffects(0x4ee2820, 0x4de15e0, 0x4c55b00)
	/home/runner/work/tbc/tbc/sim/core/spell.go:209 +0xc
github.com/wowsims/tbc/sim/core.(*Spell).makeCastFuncWait.func1(0x4de15e0, 0x4c55b00)
	/home/runner/work/tbc/tbc/sim/core/cast.go:253 +0xa
github.com/wowsims/tbc/sim/core.(*Spell).makeCastFuncWait.func3(0x4de15e0, 0x4c55b00)
	/home/runner/work/tbc/tbc/sim/core/cast.go:284 +0xf
github.com/wowsims/tbc/sim/core.(*Spell).wrapCastFuncResources.func1(0x4de15e0, 0x4c55b00, 0x10cd0008)
	/home/runner/work/tbc/tbc/sim/core/cast.go:118 +0x4
github.com/wowsims/tbc/sim/core.(*Spell).Cast(...)
	/home/runner/work/tbc/tbc/sim/core/spell.go:188
github.com/wowsims/tbc/sim/core.(*AutoAttacks).TrySwingOH(0x4cd1820, 0x4de15e0, 0x4c55b00)
	/home/runner/work/tbc/tbc/sim/core/attack.go:482 +0x28
github.com/wowsims/tbc/sim/core.(*AutoAttacks).SwingMelee(0x4cd1820, 0x4de15e0, 0x4c55b00)
	/home/runner/work/tbc/tbc/sim/core/attack.go:430 +0x3
github.com/wowsims/tbc/sim/core.(*AutoAttacks).resetAutoSwing.func1(0x4de15e0)
	/home/runner/work/tbc/tbc/sim/core/attack.go:349 +0x6
github.com/wowsims/tbc/sim/core.(*Simulation).runOnce(0x4de15e0)
	/home/runner/work/tbc/tbc/sim/core/sim.go:282 +0x11
github.com/wowsims/tbc/sim/core.(*Simulation).run(0x4de15e0, 0x4c81420)
	/home/runner/work/tbc/tbc/sim/core/sim.go:220 +0x1b
github.com/wowsims/tbc/sim/core.runSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4cc6230, 0x4cc0cc0, 0x4e26680, 0x4cc0d20, 0x3fa3c00, ...)
	/home/runner/work/tbc/tbc/sim/core/sim.go:99 +0x4
github.com/wowsims/tbc/sim/core.RunSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4cc6230, 0x4cc0cc0, 0x4e26680, 0x4cc0d20, 0x0)
	/home/runner/work/tbc/tbc/sim/core/sim.go:39 +0x2
created by github.com/wowsims/tbc/sim/core.RunRaidSimAsync
	/home/runner/work/tbc/tbc/sim/core/api.go:74 +0x4

Request:
eJztUj1oFEEY3fft7bI3njKsFuM1notFDARmczmIVcbOIITDQlJGwaBgY0iRWB2SwEaLHFd5sUiCoGIVGwkeyJE0/mJAi5wIFyGICMYIgsiZ4MxugnamuMLCNzDz5n0z35ufj31x2bTLNp1rcIuXz41fGPEcns4+BOP851eIaB2BW91CowWW4q+2wTxe0frqe8NeTJJ4M0WaPZggsVwz2uI2RKsBtp//0OueT1Fgm80ZvvJJp3rdilMd5M82IJofEKQbsaJ17VhvQnx/p5dp5WXsWKuQ7h+tGX43Mvx207isf4O4NUE7bHbBxJcmKTiwQKkSISI8odSY3blC1n+0FVc9DwqCejEyDXaWY4xKQAQcT+IDKkzIMXUiHutn1MlEOaT6E+W8qiKRxtV8wtSsKuIihjCIMuB3efZHSuVsiV77FA1iDs49OItw6nBWgTXQJpzko8vkZF0OgRyuI8j3SNmTl2FedsuwSxZ0k7JghrDbdGFhBtZbWGyn+b6Hm6CO+Bp2bEAsw37Hrb3PfOqgziMc+j2K+sxDOuel4RgbfVeSm1eUf8NOx7w0rI7uvsvhmarB0z7/M+X6Bf2zdTuq2pLGfvyXPKfb4/MHkmKMlneL0VLmh7L7vPIAr92/s5SR+AW9IYyi

**Comment by SytseGroenwold** [comment]
More specifically, double Blinkstrike is what causes it for me. A single Blinkstrike works fine.
