### ISSUE TITLE
Crash Report 2066325088

### ISSUE THREAD

**Issue by ssabbyccatt** [wowsims/tbc#1090]
runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 35 [running]:
runtime/debug.Stack(0xa3cbb0, 0x4f6e540, 0x40)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/tbc/sim/core.runSim.func1(0x4571f80, 0x6c94a20)
	/home/runner/work/tbc/tbc/sim/core/sim.go:53 +0x8
panic(0x99480, 0xa3cbb0)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:965 +0x19
github.com/wowsims/tbc/sim/core.(*Spell).Cast(...)
	/home/runner/work/tbc/tbc/sim/core/spell.go:188
github.com/wowsims/tbc/sim/druid/balance.(*BalanceDruid).actRotation(0x3f69500, 0x4de0d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1000100000004)
	/home/runner/work/tbc/tbc/sim/druid/balance/rotation.go:69 +0xe
github.com/wowsims/tbc/sim/druid/balance.(*BalanceDruid).tryUseGCD(0x3f69500, 0x4de0d20)
	/home/runner/work/tbc/tbc/sim/druid/balance/rotation.go:33 +0x16
github.com/wowsims/tbc/sim/druid/balance.(*BalanceDruid).OnGCDReady(0x3f69500, 0x4de0d20)
	/home/runner/work/tbc/tbc/sim/druid/balance/rotation.go:13 +0x2
github.com/wowsims/tbc/sim/core.(*Character).initialize.func1(0x4de0d20)
	/home/runner/work/tbc/tbc/sim/core/character.go:299 +0x11
github.com/wowsims/tbc/sim/core.(*Simulation).runOnce(0x4de0d20)
	/home/runner/work/tbc/tbc/sim/core/sim.go:282 +0x11
github.com/wowsims/tbc/sim/core.(*Simulation).run(0x4de0d20, 0x3dd2a70)
	/home/runner/work/tbc/tbc/sim/core/sim.go:220 +0x1b
github.com/wowsims/tbc/sim/core.runSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4df8d20, 0x6c949c0, 0x4ce3600, 0x6c94a20, 0x74af600, ...)
	/home/runner/work/tbc/tbc/sim/core/sim.go:99 +0x4
github.com/wowsims/tbc/sim/core.RunSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4df8d20, 0x6c949c0, 0x4ce3600, 0x6c94a20, 0x0)
	/home/runner/work/tbc/tbc/sim/core/sim.go:39 +0x2
created by github.com/wowsims/tbc/sim/core.RunRaidSimAsync
	/home/runner/work/tbc/tbc/sim/core/api.go:74 +0x4

Request:
eJzjambj2sHKtZS1iZEtICexMrWIg0OAUeo4I5eAwLtJTBLtTxiV2NZ0M13/zcjFIrCrlQkofvITo8S1h0BxoOBdoDiHwOk/jBL/mpi4hAUOA+UO72ZU4jzymxGCuHgF+nqZJC52Mikxb5gO0v+8h0niwx2g/iMQ/ZwCv3uBkiC1wgI/u5gkLu2FG3AXbEBPH5PEw8lQNUBn9DAByf5/IPbSDhD72V+QM252Mkks2AAS3dYCFm1lUhLcwMTYwMR8gonxAhNjBVMDI5PWBSaGUUBVUMXCwSjAZGTGxcbBIsCowCikwcEqwCTBpMCswWjAZMHswOjBHMAYwZTAnMFYwPyDkXUGE/MBJpYVTIxSTFwMXYyKpgYGxkZGxoZGRgbGhkAKSOjqAgVNDYxNDEBCsxgZbjEycEGhEBsHI9AkJi4eLoQYA/E8IaB7FZi0OICuZpQAufczEyfYIwtKHBQhXhJxkJw1EwRO2gtdBXpluKcakX0O9LZSiptjgp/Ami3bFvAYMAIAgHJyNQ==

**Comment by lologarithm** [comment]
Hey @ssabbyccatt thanks for the report. We are in the middle of writing the wotlk sim and so are unlikely to have time to fix this immediately. 

If this is a huge blocker let me know and I might be able to figure it out sooner than later :)
