### ISSUE TITLE
Crash Report 2030972609

### ISSUE THREAD

**Issue by xAc74x** [wowsims/tbc#1092]
runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 463 [running]:
runtime/debug.Stack(0x4de2930, 0x545d9c0, 0x33)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/tbc/sim/core.runSim.func1(0x3fbdf80, 0x7e35b00)
	/home/runner/work/tbc/tbc/sim/core/sim.go:53 +0x8
panic(0xf2e60, 0x4de2930)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:965 +0x19
github.com/wowsims/tbc/sim/core.removeBySwappingToBack(...)
	/home/runner/work/tbc/tbc/sim/core/aura.go:624
github.com/wowsims/tbc/sim/core.(*Aura).Deactivate(0x298e6c0, 0x4dde700)
	/home/runner/work/tbc/tbc/sim/core/aura.go:587 +0xfc
github.com/wowsims/tbc/sim/core.(*auraTracker).advance(0x3e28360, 0x4dde700)
	/home/runner/work/tbc/tbc/sim/core/aura.go:384 +0xf
github.com/wowsims/tbc/sim/core.(*Unit).advance(0x3e28000, 0x4dde700, 0x25362cca)
	/home/runner/work/tbc/tbc/sim/core/unit.go:369 +0x4
github.com/wowsims/tbc/sim/core.(*Character).advance(0x3e28000, 0x4dde700, 0x25362cca)
	/home/runner/work/tbc/tbc/sim/core/character.go:348 +0x4
github.com/wowsims/tbc/sim/core.(*Simulation).advance(0x4dde700, 0x25362cca)
	/home/runner/work/tbc/tbc/sim/core/sim.go:330 +0x23
github.com/wowsims/tbc/sim/core.(*Simulation).runOnce(0x4dde700)
	/home/runner/work/tbc/tbc/sim/core/sim.go:279 +0x13
github.com/wowsims/tbc/sim/core.(*Simulation).run(0x4dde700, 0x4c49e50)
	/home/runner/work/tbc/tbc/sim/core/sim.go:237 +0x20
github.com/wowsims/tbc/sim/core.runSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4df6690, 0x7e35aa0, 0x6c67040, 0x7e35b00, 0x1432600, ...)
	/home/runner/work/tbc/tbc/sim/core/sim.go:99 +0x4
github.com/wowsims/tbc/sim/core.RunSim(0x14158a8, 0x0, 0x0, 0x0, 0x0, 0x4df6690, 0x7e35aa0, 0x6c67040, 0x7e35b00, 0x0)
	/home/runner/work/tbc/tbc/sim/core/sim.go:39 +0x2
created by github.com/wowsims/tbc/sim/core.RunRaidSimAsync
	/home/runner/work/tbc/tbc/sim/core/api.go:74 +0x4

Request:
eJztkz9oU1EUxvOd+5Lc3Fp7eVZ5DQgxg4ZC4b6EDJnydBNBnMTRDkIHBxGR6hSibaNJa0FELQ4ZFAo6RAcb/1KsQ92Cgtbi0KKDi1CclBj1JC/9Yx10yODgeY/LPb/z3e9cuPeqb2F1N6yuhPMIHTo+eObYSQktom+htL5ZImfsA+KhO0V6U4ey9I0iMX/1Gc7rZeaLdTR5t35WJOd7nuLiOafb9GNeOPcI8Qin/s+aS+PkjFbga7SeZs3KOzapXKUmiejGOBtwxgYj7PfyyZpBE3briQlyli+3NVLfZ02hAp49LPkzSzdKxOP7RpOWmZZb9BzvOqJvl/yl8Z1VsmYJORLzhBphGDlgASInqCDQX6PA/+honA1JeNC0b0jtkbB7teibut6MF9ldvmIpGyXNx93mD7J2RpLmE0EsmBBGDAdzCE6CysAXommICkQVmIWoIbgAWgI+glYQLJCIkqSL2J1MGeOmTco1JjWQNmljksZlmHK5kE66yfQAV6ZwDapHCVkdtKW/l15PRdVWeWFH7MdqYENNK0vWq9t/JXrm3iaNPv8b4Wu5ifB1XSUZr7WNr4fXJYsIqPZn9/CrpASOYggnMA+oLWq9GPj7zLZilKB+yXZwECM7LyKtdrnTXp/fuJa1P1Fsv0P/7Es45XXERjz9g8+BzvTZEJnWWJjz9raBd4TPNNolJw/qWyOjM10GPwFdsqTW

**Comment by lologarithm** [comment]
Hey @xAc74x thanks for the report. We are in the middle of writing the wotlk sim and so are unlikely to have time to fix this immediately. 

If this is a huge blocker let me know and I might be able to figure it out sooner than later :)
